### ISSUE TITLE
Missing Argument Error During php artisan fetch Execution

### ISSUE THREAD

**Issue by mfaathirarsa** [cwang22/buy-all-steam-games#70]
I encountered an issue while attempting to execute the `php artisan fetch` command. The command fails with the following error message:

```
Not enough arguments (missing: "countries").
```

It appears that the command requires an additional argument, specifically the "countries" parameter. I have reviewed the documentation and ensured that I am using the command correctly according to the provided instructions. However, the issue persists.

Could you please provide guidance on the correct usage of this command, or update the documentation to reflect the required arguments? Your assistance in resolving this issue would be greatly appreciated.

Thank you.

**Comment by cwang22** [comment]
Please try this
````
php artisan fetch US
````
